# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  首页: /
  项目介绍: /archives
  关于我们: /about
  # Tags: /tags
  # Categories: /categories
  联系我们: /contact

# favicon: /favicon.ico

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Social Accounts
# email_url: test@example.com

# Footer About Text
# footer_about: "This theme was developed by <a href=\"https://github.com/klugjo\">Jonathan Klughertz</a>. The source code is available on Github. Create Websites. Make Magic."

# Footer Copyright Line
footer_copyright: "齐码蓝智能科技（大理市）有限责任公司 版权所有"

